name: Nuclei Security Scan

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - 'start.sh'

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    container: projectdiscovery/nuclei:v3.4
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Container
        run: apk add --quiet nodejs npm docker bash sudo
      
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Start Docker containers
        run: |
          chmod +x ./start.sh
          ./start.sh --ci
        
      - name: Wait for application to be ready
        run: |
          echo "Waiting for the application to start..."
          sleep 30  # Adjust the sleep time as necessary

      - name: Run Nuclei scan
        run: |
          nuclei -target http://localhost:3000 -timeout 5 -page-timeout 10 -silent -me nuclei-reports/ || true

      - name: Upload Nuclei reports
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-security-reports
          path: nuclei-reports/
          retention-days: 14   